[package]
name = "workflow-tutorial"
version = "0.1.0"
authors = ["Tomas Olvecky <tomas.olvecky@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.48.0"

[profile.release]
opt-level = "s"
debug = "line-tables-only"
