[package]
name = "webhook-tutorial"
version = "0.1.0"
authors = ["Tomas Olvecky <tomas.olvecky@gmail.com>"]
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.48.0"
wstd = "0.6.3"

[profile.release]
opt-level = "s"
debug = "line-tables-only"

