[package]
name = "activity-sleepy"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen.workspace = true

[profile.release]
opt-level = "s"
